name: CI

on:
  pull_request:
  merge_group:

env:
  GH_TOKEN: ${{ github.token }}

defaults:
  run:
    shell: bash

jobs:
  ci:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install QEMU (ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install qemu-system-x86
      - name: Install QEMU (macos)
        if: matrix.os == 'macos-latest'
        run: |
          # TODO: Enable once it works again
          # brew update
          brew install qemu
      - name: Install QEMU (windows)
        if: matrix.os == 'windows-latest'
        run: |
          choco install qemu
          echo "C:\Program Files\qemu" >> $GITHUB_PATH
      - uses: actions/checkout@v4
      - uses: mkroening/rust-toolchain-toml@main
      - name: Download rust-std-hermit
        run: gh release download 1.84.1 --repo hermit-os/rust-std-hermit --pattern rust-std-1.84.1-x86_64-unknown-hermit.tar.gz
      - name: Install rust-std-hermit
        run: |
          tar xvf rust-std-1.84.1-x86_64-unknown-hermit.tar.gz
          ./rust-std-1.84.1-x86_64-unknown-hermit/install.sh
      - name: Download loader
        run: gh release download --repo hermit-os/loader --pattern hermit-loader-x86_64
      - name: Building dev version
        run: cargo build --target x86_64-unknown-hermit --locked
      - name: Run dev version
        run: |
          qemu-system-x86_64 \
            -cpu qemu64,apic,fsgsbase,fxsr,rdrand,rdtscp,xsave,xsaveopt \
            -smp 1 -m 128M \
            -display none -serial stdio \
            -kernel hermit-loader-x86_64 \
            -initrd target/x86_64-unknown-hermit/debug/hermit-rs-template
      - name: Building release version
        run: cargo build --target x86_64-unknown-hermit --locked --release
      - name: Run release version
        run: |
          qemu-system-x86_64 \
            -cpu qemu64,apic,fsgsbase,fxsr,rdrand,rdtscp,xsave,xsaveopt \
            -smp 1 -m 128M \
            -display none -serial stdio \
            -kernel hermit-loader-x86_64 \
            -initrd target/x86_64-unknown-hermit/release/hermit-rs-template
