name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Install QEMU, NASM
        run: |
          sudo apt-get update
          sudo apt-get install qemu-system-x86 nasm
      - uses: actions/checkout@v3
      - uses: mkroening/rust-toolchain-toml@main
      - name: Download rust-std-hermit
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: hermitcore/rust-std-hermit
          version: tags/1.70.0
          file: rust-std-1.70.0-x86_64-unknown-hermit.tar.gz
      - name: Install rust-std-hermit
        run: |
          tar xvf rust-std-1.70.0-x86_64-unknown-hermit.tar.gz
          ./rust-std-1.70.0-x86_64-unknown-hermit/install.sh
      - name: Download loader
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: hermitcore/rusty-loader
          file: rusty-loader-x86_64
      - name: Building dev version
        run: cargo build --target x86_64-unknown-hermit --locked
      - name: Run dev version
        run: |
          qemu-system-x86_64 \
            -cpu qemu64,apic,fsgsbase,fxsr,rdrand,rdtscp,xsave,xsaveopt \
            -smp 1 -m 64M \
            -device isa-debug-exit,iobase=0xf4,iosize=0x04 \
            -display none -serial stdio \
            -kernel rusty-loader-x86_64 \
            -initrd target/x86_64-unknown-hermit/debug/hello_world
      - name: Building release version
        run: cargo build --target x86_64-unknown-hermit --locked --release
      - name: Run release version
        run: |
          qemu-system-x86_64 \
            -cpu qemu64,apic,fsgsbase,fxsr,rdrand,rdtscp,xsave,xsaveopt \
            -smp 1 -m 64M \
            -device isa-debug-exit,iobase=0xf4,iosize=0x04 \
            -display none -serial stdio \
            -kernel rusty-loader-x86_64 \
            -initrd target/x86_64-unknown-hermit/release/hello_world
